# Generated by Django 3.1.5 on 2021-06-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='mobile',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
