# Generated by Django 3.1.5 on 2021-06-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20210627_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='image/')),
                ('icon', models.ImageField(upload_to='image/')),
                ('votes_total', models.IntegerField(default=1)),
                ('body', models.TextField()),
                ('url', models.TextField()),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userregistration')),
            ],
        ),
    ]
